export const datosHeader = {
    titulo: 'Airzone Project'
}

export const confFaseCreacion = {
    mostrarTitulo: true,
    titulo: 'creación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: true,
    mostrarDescripcion: true,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'recopilación',
    responsableSiguienteFase: 'Jefatura de producto'
}

export const confFaseRecopilacion = {
    mostrarTitulo: true,
    titulo: 'recopilación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: true,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'análisis',
    responsableSiguienteFase: 'I+D'
}

export const confFaseAnalisis = {
    mostrarTitulo: true,
    titulo: 'análisis',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: true,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'aprobación',
    responsableSiguienteFase: 'Jefe de proyecto'
}
export const confFaseAprobacion = {
    mostrarTitulo: true,
    titulo: 'aprobación ',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAprobacion: true,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'planificación',
    responsableSiguienteFase: 'I+D'
}
export const confFasePlanificacion = {
    mostrarTitulo: true,
    titulo: 'planificación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: true,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'especificación',
    responsableSiguienteFase: 'Jefatura de producto'
}
export const confFaseEspecificacion = {
    mostrarTitulo: true,
    titulo: 'especificación',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: true,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'desarrollo',
    responsableSiguienteFase: 'I+D'
}
export const confFaseDesarrollo = {
    mostrarTitulo: true,
    titulo: 'desarrollo',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: true,
    mostrarInformeDiseno: true,
    mostrarDocSOO: true,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'validación interna',
    responsableSiguienteFase: 'I+D'
}
export const confFaseValidacionInterna = {
    mostrarTitulo: true,
    titulo: 'validación interna',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: true,
    mostrarDocMantis: true,
    mostrarManual: true,
    mostrarTestProbado: true,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'validación calidad',
    responsableSiguienteFase: 'Calidad de producto'
}
export const confFaseValidacionCalidad = {
    mostrarTitulo: true,
    titulo: 'validación calidad',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: true,
    mostrarDocMantis: true,
    mostrarManual: false,
    mostrarTestProbado: true,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'fabricación primera unidad',
    responsableSiguienteFase: 'Fábrica'
}
export const confFaseFabPrimeraUnidad = {
    mostrarTitulo: true,
    titulo: 'fabricación primera unidad',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: true,
    mostrarComentariosFabPrimeraUnidad: true,
    mostrarPrimeraUnidadTesteada: false,
    mostrarComentariosValPrimeraUnidad: false,
    mostrarFechaResponsableSigFase: true,
    siguienteFase: 'validación primera unidad',
    responsableSiguienteFase: 'Calidad de producto'
}
export const confFaseValidacionPrimeraUnidad = {
    mostrarTitulo: true,
    titulo: 'validación primera unidad',
    mostrarFechaInicio: true,
    mostrarJefeProyecto: false,
    mostrarDescripcion: false,
    mostrarDocReq: false,
    mostrarAnalisis: false,
    mostrarAprobacion: false,
    mostrarPlanif: false,
    mostrarDocEsp: false,
    mostrarDescDiseno: false,
    mostrarInformeDiseno: false,
    mostrarDocSOO: false,
    mostrarDocPruebas: false,
    mostrarDocMantis: false,
    mostrarManual: false,
    mostrarTestProbado: false,
    mostrarPrimeraUnidadFabrciada: false,
    mostrarComentariosFabPrimeraUnidad: false,
    mostrarPrimeraUnidadTesteada: true,
    mostrarComentariosValPrimeraUnidad: true,
    mostrarFechaResponsableSigFase: false
}